"use strict";

let logger 		= require("../../../core/logger");
let config 		= require("../../../config");
let C 	 		= require("../../../core/constants");
let E 			= require("../../../core/errors");
let path 		= require("path");
let async 		= require("async");
let crypto 		= require("crypto");
let mailer 		= require("../../../libs/mailer");

let _			= require("lodash");

let User 		= require("./models/user");
let pug 		= require("pug");

module.exports = {
	name: "users",
	//version: 1,

	settings: {
		//latestVersion: true,
		rest: true,
		ws: true,
		graphql: true,
		permission: C.PERM_ADMIN,
		collection: User,
		
		hashedIdentity: true,
		modelPropFilter: "code fullName email username provider profile socialLinks roles verified apiKey lastLogin locale status createdAt updatedAt"
	},
	
	actions: {
		list: {
			cache: {
				keys: [ "limit", "offset", "sort", "filter", "author" ]
			},
			defaultMethod: "get",
			handler(ctx) {
				let filter = {};

				let query = this.collection.find(filter);
				return this.applyFilters(query, ctx).exec()
				.then(docs => this.toJSON(docs))
				.then(json => this.populateModels(ctx, json));
			}
		},

		// return a user by ID
		get: {
			cache: {
				keys: [ "code" ]
			},
			defaultMethod: "get",
			needModel: true,
			handler(ctx) {
				return this.Promise.resolve(ctx)
				.then(ctx => ctx.call(this.name + ".model", { code: ctx.params.code }))
				.then(model => this.checkModel(model, "app:UserNotFound"))
				.then(doc => this.toJSON(doc))
				.then(json => this.populateModels(ctx, json));
			}
		},

		model: {
			cache: true,
			publish: false,
			handler(ctx) {
				return this.resolveModel(ctx);
			}
		},

		create: {
			defaultMethod: "post",
			handler(ctx) {
				let resetToken;
				return this.Promise.resolve(ctx)
				.then(() => {
					resetToken = crypto.randomBytes(25).toString("hex");
					let resetTokenExpiry = Date.now() + 24 * 3600000; // expire in 24 hours
					let user = new User({
						fullName: ctx.params.fullName,
						email: ctx.params.email,
						username: ctx.params.username,
						password: crypto.randomBytes(25).toString("hex"), // need an acceptable password to pass validation
						roles: ctx.params.roles,
						resetPasswordToken: resetToken, // specially generated by us
						resetPasswordExpires: resetTokenExpiry, // specially generated by us
						apiKey: ctx.params.apiKey,
						status: ctx.params.status,
					});
					user.passwordLess = true; // No password for this account. He/she can login via social login or passwordless login
					user.verified = true; // No need to verify a social signup

					return user.save().catch(err => {
						if (err && err.code === 11000) {
							let field = err.message.split("index: ")[1];
							field = field.split(" dup key")[0];
							field = field.substring(0, field.lastIndexOf("_"));
							if (field.indexOf("$"))
								field = field.split("$")[1];
							let newErr = new Error("Unable to create user!");
							newErr.params = {
								field: field
							};
							newErr.msgCode = "app:DuplicateFieldError" + _.capitalize(field);
							newErr.type = "BAD_REQUEST";
							newErr.status = 400;
							throw newErr;
						}
						throw err;
					});
				})
				.then(doc => this.toJSON(doc))
				.then(json => this.populateModels(ctx, json))
				.then(json => {
					this.notifyModelChanges(ctx, "created", json, ctx.params.$user);

					// Clear cached values
					this.clearCache();

					return json;
				})
				.then(json => {
					let subject = "mailSubjectResetPassword";
					pug.renderFile(path.join(__dirname, "../../../views/mail/passwordReset.pug"), {
						name: ctx.params.fullName,
						resetLink: config.app.url + "reset/" + resetToken,
						app: config.app
					}, function(err, html) {
						if (err) 
							return Promise.reject(new Error("Unable to render e-mail! " + err.message));

						mailer.send(ctx.params.email, subject, html, function(err, info) {
							if (err)
								this.notifyModelChanges(ctx, "error", "UnableToSendEmail", ctx.params.$user);
							else
								this.notifyModelChanges(ctx, "info", "emailSentPasswordResetLink", ctx.params.$user);
						});
					});
					return json;
				});	
			}
		},

		update: {
			defaultMethod: "put",
			needModel: true,
			handler(ctx) {
				return this.Promise.resolve(ctx)
				.then(ctx => this.resolveID(ctx))
				.then(modelID => this.checkModel(modelID, "app:UserNotFound"))
				.then(modelID => this.collection.findById(modelID).exec())
				.then(doc => {
					if (ctx.params.fullName != null) doc.fullName = ctx.params.fullName;
					if (ctx.params.email != null) doc.email = ctx.params.email;
					if (ctx.params.username != null) doc.username = ctx.params.username;
					if (ctx.params.roles != null) doc.roles = ctx.params.roles;
					if (ctx.params.apiKey != null) doc.apiKey = ctx.params.apiKey;
					if (ctx.params.status != null) doc.status = ctx.params.status;

					return doc.save().catch(err => {
						if (err && err.code === 11000) {
							let field = err.message.split("index: ")[1];
							field = field.split(" dup key")[0];
							field = field.substring(0, field.lastIndexOf("_"));
							if (field.indexOf("$"))
								field = field.split("$")[1];
							let newErr = new Error("Unable to update user!");
							newErr.params = {
								field: field
							};
							newErr.msgCode = "app:DuplicateFieldError" + _.capitalize(field);
							newErr.type = "BAD_REQUEST";
							newErr.status = 400;
							throw newErr;
						}
						throw err;
					});
				})
				.then(doc => this.toJSON(doc))
				.then(json => this.populateModels(ctx, json))
				.then((json) => {
					this.notifyModelChanges(ctx, "updated", json, ctx.params.$user);
					
					// Clear cached values
					this.clearCache();

					return json;
				});	
			}							
		},

		remove: {
			defaultMethod: "delete",
			needModel: true,
			handler(ctx) {
				console.log('remote', ctx);
				return this.Promise.resolve(ctx)
				.then(ctx => ctx.call(this.name + ".model", { code: ctx.params.code }))
				.then(model => this.checkModel(model, "app:UserNotFound"))
				.then(model => {
					return this.collection.remove({ _id: model.id }).then(() => model);
				})
				.then(doc => this.toJSON(doc))
				.then(json => this.populateModels(ctx, json))
				.then((json) => {
					this.notifyModelChanges(ctx, "removed", json, ctx.params.$user);
					
					// Clear cached values
					this.clearCache();

					return json;
				});		
			}
		}

	},

	// Event listeners
	events: {

	},

	// Service methods
	methods: {

	},

	created() {
		// this.logger.info("Service created!");
	},

	started() {
		// this.logger.info("Service started!");
	},

	stopped() {
		// this.logger.info("Service stopped!");
	},

	graphql: {

		query: `
			users(limit: Int, offset: Int, sort: String): [User]
			user(code: String): User
		`,

		// SWYX: not sure about the [String] as these are technically objects
		types: `
			type User {
				fullName: String
				email: String
				username: String
				passwordLess: Boolean
				provider: String
				profile: SocialProfile
				socialLinks: SocialLinks
				roles: [String]
				verified: Boolean
				apiKey: String
				lastLogin: Timestamp
				locale: String
				status: Int
			}

			type SocialProfile {
				name: String
				gender: String
				picture: String
				location: String
			}

			type SocialLinks {
				facebook: String
				twitter: String
				google: String
				github: String
			}

		`,

		mutation: `
			userCreate(fullName: String, email: String, username: String, apiKey: String, status: Int): User
			userUpdate(code: String!, fullName: String, email: String, username: String, verified: Boolean, apiKey: String, status: Int): User
			userRemove(code: String!): User
		`,

		resolvers: {
			Query: {
				users: "list",
				user: "get"
			},

			Mutation: {
				userCreate: "create",
				userUpdate: "update",
				userRemove: "remove"
			}
		}
	}

};

/*
## GraphiQL test ##


*/
